---
  - name: Ensure that dir is created
    file:
      path: /home/backup/mysql
      owner: backup
      group: backup
      mode: 0755
      state: directory

  - name: conf file
    template:
      src: .my.cnf.j2
      dest: /home/backup/.my.cnf
    no_log: true

  - name: MySQL-exporter user
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user_backup }}"
      password: "{{ mysql_exporter_pass_backup }}"
      host: "%"
      priv:
        '*.*': 'LOCK TABLES,SELECT'
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: conf file
    template:
      src: mysql-backup.j2
      dest: /etc/cron.d/mysql-backup
    no_log: true

  - name: Ensure that cron file is created
    file:
      path: /etc/cron.d/mysql-backup
      owner: root
      group: backup
      mode: 0755
      state: file
