---
  - name: stop systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: no

  - name: move resolf.conf
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
