---
  - name: Create grafana directories
    ansible.builtin.file:
      path: "/opt/grafana/provisioning/{{ item }}"
      state: directory
      recurse: yes
    loop:
      - dashboards
      - datasources

  - name: Setup prometheus datasource
    template:
      src: prometheus.yaml.j2
      dest: /opt/grafana/provisioning/datasources/prometheus.yaml

  - name: Setup influxDB datasource
    template:
      src: influx.yaml.j2
      dest: /opt/grafana/provisioning/datasources/influx.yaml

  - name: Setup telegraf datasource
    template:
      src: telegraf.yaml.j2
      dest: /opt/grafana/provisioning/datasources/telegraf.yaml

  - name: Copy conf for dashboards
    template:
      src: dashboard.yaml.j2
      dest: /opt/grafana/provisioning/dashboards/sample.yaml

  - name: Setup dashboards
    copy:
      src: main.json
      dest: /opt/grafana/provisioning/dashboards/main.json

  - name: Setup second dashboard
    copy:
      src: syslog.json
      dest: /opt/grafana/provisioning/dashboards/syslog.json

  - name: Setup mysql dashboard
    copy:
      src: mysql.json
      dest: /opt/grafana/provisioning/dashboards/mysql.json

  - name: Copy config for grafana
    template:
        src: grafana.ini.j2
        dest: /opt/grafana/grafana.ini
    no_log: true

  - name: Install and start grafana in Docker
    community.docker.docker_container:
      name: grafana
      image: grafana/grafana
      restart_policy: always
      volumes: /opt/grafana:/etc/grafana
      published_ports: "{{ grafana_port }}:3000"
      container_default_behavior: no_defaults
