---
  - name: Create grafana directories
    ansible.builtin.file:
      name: "/opt/grafana/provisioning/{{ item }}"
      recurse: yes
      state: directory
    loop:
      - dashboards
      - datasources

  - name: Copy grafana.ini to server
    ansible.builtin.template:
      src: roles/grafana/templates/grafana.ini.j2
      dest: /opt/grafana/grafana.ini

  - name: Copy prometheus datasource to server
    ansible.builtin.template:
      src: roles/grafana/templates/prometheus.yaml.j2
      dest: /opt/grafana/provisioning/datasources/prometheus.yaml

  - name: Copy influxdb datasource to server
    ansible.builtin.template:
      src: roles/grafana/templates/influxdb.yaml.j2
      dest: /opt/grafana/provisioning/datasources/influxdb.yaml

  - name: Copy telegraf datasource to server
    ansible.builtin.template:
      src: roles/grafana/templates/telegraf.yaml.j2
      dest: /opt/grafana/provisioning/datasources/telegraf.yaml

  - name: Copy dashboards to server
    ansible.builtin.copy:
      src: "roles/grafana/files/{{ item }}"
      dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
    loop:
      - default.yaml
      - main.json
      - mysql.json
      - syslog.json

  - name: install grafana docker container
    community.docker.docker_container:
      name: grafana
      image: grafana/grafana
      volumes: /opt/grafana:/etc/grafana
      container_default_behavior: no_defaults
      published_ports: "{{ grafana_port }}:3000"
