---
  - name: Add apt key for grafana
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key

  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main

  - name: Install grafana
    apt:
      name: grafana
    notify: Reset Grafana Password

  - name: Start grafana
    service:
        name: grafana-server
        state: started
        enabled: yes

  - name: Move Grafana conf
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
    notify: restart grafana

  - name: Setup prometheus datasource
    template:
      src: prometheus.yaml.j2
      dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    notify: restart grafana

  - name: Setup influxDB datasource
    template:
      src: influx.yaml.j2
      dest: /etc/grafana/provisioning/datasources/influx.yaml
    notify: restart grafana
  
  - name: Setup telegraf datasource
    template:
      src: telegraf.yaml.j2
      dest: /etc/grafana/provisioning/datasources/telegraf.yaml
    notify: restart grafana

  - name: Copy conf for dashboards
    template:
      src: dashboard.yaml.j2
      dest: /etc/grafana/provisioning/dashboards/sample.yaml

  - name: Setup dashboards
    copy:
      src: main.json
      dest: /etc/grafana/provisioning/dashboards/main.json
    notify: restart grafana

  - name: Setup second dashboard
    copy:
      src: syslog.json
      dest: /etc/grafana/provisioning/dashboards/syslog.json
    notify: restart grafana
