---
  - name: Install bind9
    apt:
      name: bind9
      state: latest

  - name: Start bind9
    service:
        name: bind9
        state: started
        enabled: yes

  - name: move bind9 conf
    template:
      src: named.conf.options.j2
      dest: /etc/bind/named.conf.options
    notify: Restart bind9 service

  - name: move conf.local
    template:
      src: named.conf.local.j2
      dest: /etc/bind/named.conf.local
    notify: Restart bind9 service

  - name: move db conf
    template:
      src: db.odns
      dest: /etc/bind/
    notify: restart bind with rndc
