---
  - name: Install agama dependecies
    apt:
        name:
          - python3-flask-sqlalchemy
          - python3-pymysql
        state: latest

  - name: Download agama.py
    get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama
