- name: make agama directory
  ansible.builtin.file:
    name: /opt/agama
    state: directory

- name: install docker file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: build agama container
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: start agama container
  community.docker.docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}"
    published_ports: "{{ agama_port }}:8000"
