---
  - name: Create user backup with ssh key
    ansible.builtin.user:
      name: backup
      home: /home/backup
      shell: /bin/bash
      generate_ssh_key: yes

  - name: Ensure that dir is created
    file:
      path: /home/backup/restore
      owner: backup
      group: backup
      mode: 0644
      state: directory

  - name: Ensure that Duplicity is intalled
    apt:
      name: duplicity

  - name: Create known_hosts file
    template:
      owner: root
      group: root
      mode: 0644
      src: known_hosts.j2
      dest: /home/backup/.ssh/known_hosts
