---
  - name: Install mysql-exporter
    apt:
      name: prometheus-mysqld-exporter
      state: latest

  - name: Move mysql_exporter conf
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify: mysql_exporter conf

  - name: Start mysql-exporter
    service:
        name: prometheus-mysqld-exporter
        # state: started
        enabled: yes
