---
  - name: Install MySQL exporter
    apt:
        name: prometheus-mysqld-exporter
        state: present
    register: prom_exporter_installed

  - name: Move mysql_exporter conf
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify: mysql_exporter conf

  - name: Pause for 10 sec
    pause:
      seconds: 10
    when: prom_exporter_installed.changed

  - name: Move prometheus-mysqld-exporter conf
    template:
      src: prometheus-mysqld-exporter
      dest: /etc/default/prometheus-mysqld-exporter
    notify: mysql_exporter conf

  - name: Start mysql-exporter111
    service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes
