---
  - name: Install mysql-exporter
    apt:
      name: prometheus-mysqld-exporter

  - name: Move mysql_exporter conf
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify: mysql_exporter conf

  - name: Move prometheus-mysqld-exporter conf
    template:
      src: prometheus-mysqld-exporter
      dest: /etc/default/prometheus-mysqld-exporter
    notify: mysql_exporter conf

  - name: Pause for 10 sec to find configuration
    pause:
      seconds: 10

  - name: Start mysql-exporter111
    service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes
