---
  - name: Restart keepalived
    service:
      name: keepalived
      state: restarted

  - name: Reload systemd
    ansible.builtin.shell: systemctl daemon-reload

  - name: Restart prometheus-keepalived-exporter
    service:
      name: prometheus-keepalived-exporter
      state: restarted
