---
  - name: Restart keepalived
    service:
      name: keepalived
      state: restarted

  - name: Reload systemd
    ansible.builtin.systemd:
      name: keepalived_exporter
      state: restarted
      daemon_reload: yes
