---
  - name: Install MySQL server
    apt:
      name:
        - mysql-server
        - python3-pymysql
      state: latest

  - name: Start mysql
    service:
        name: mysql
        state: started
        enabled: yes

  - name: Copy override to location
    template:
      src: override.cnf
      dest: /etc/mysql/mysql.conf.d/override.cnf
    notify: Restart mysql

  - name: MySQL database
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: MySQL user
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      host: "%"
      priv: "{{ mysql_database }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: MySQL-exporter user
    community.mysql.mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_pass }}"
      host: "%"
      priv:
        '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: MySQL replication user
    community.mysql.mysql_user:
      name: "{{ mysql_replication_user }}"
      password: "{{ mysql_replication_password }}"
      host: "%"
      priv: "*.*:REPLICATION SLAVE"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: readonly
    community.mysql.mysql_variables:
      variable: read_only
      value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
      mode: persist
      login_unix_socket: /var/run/mysqld/mysqld.sock
    notify:
    - Reset MySQL source
    - Reset MySQL replica
