---
  - name: Install MySQL server
    apt:
      name: mysql-server
      state: latest

  - name: Start mysql
    service:
        name: mysql
        state: started
        enabled: yes

  - name: Copy override to location
    copy:
      src: override.cfg
      dest: /etc/mysql/mysql.conf.d/override.cnf
    notify: Restart mysql
