---
    - name: Create user
    ansible.builtin.user:
      name: juri
      shell: /bin/bash

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: juri
      state: present
      key: https://github.com/hudolejev.keys

  - name: Create user
    ansible.builtin.user:
      name: roman
      shell: /bin/bash

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: romankuchin
      state: present
      key: https://github.com/romankuchin.keys

  - name: Create user for agama
    ansible.builtin.user:
      name: agama
      shell: /bin/bash

  - name: Create dir for agama user
    file:
      path: /opt/agama
      state: directory
      owner: agama
      mode: 0755
