---
  - name: Install keepalived
    apt:
      name: keepalived
  #
  # - name: ensure that keepalived folder is created
  #   file:
  #     path: /etc/keepalived
  #     state: directory

  - name: Copy keepalived file
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
    notify: Restart keepalived

  - name: Copy script
    template:
      src: keepalivedscript
      dest: /home/keepalived_script
      mode: 777
    notify: Restart keepalived

  - name: Ensure that keepalived is running
    service:
      name: keepalived
      state: started
      enabled: yes

  - name: Copy keepalived exporter binary
    copy:
      src: keepalived_exporter
      dest: /usr/local/bin/keepalived_exporter
      mode: a+x

  - name: Copy keepalived exporter service file
    template:
      src: keepalived_exporter.service
      dest: /etc/systemd/system/keepalived_exporter.service
      mode: a+x
    notify:
      - Reload systemd

  - name: Start and enable keepalived exporter
    service:
      name: keepalived_exporter
      state: started
      enabled: yes
