---
  - name: Install nginx-exporter
    apt:
      name: prometheus-nginx-exporter
      state: latest

  - name: Start nginx-exporter
    service:
        name: prometheus-nginx-exporter
        state: started
        enabled: yes

  - name: Copy exporter config
    template:
      src: exporter.j2
      dest: /etc/nginx/sites-enabled/exporter
    notify: Restart nginx exporter service
